pipeline:
  identifier: Build_ck53467_fk_1738262119472
  name: Build fk
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1738262011156
        repoName: ck53467/fk
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    command: |-
                      git clone https://github.com/ck53467/u9.git
                      cd u9
                      pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
                      chmod +x *
                      python3 megoxer.py
                  timeout: ""
                  type: Run
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-

                      python3 -m venv .venv
                      . .venv/bin/activate
                      git clone https://github.com/ck53467/u9.git
                      chmod +x *
                      pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
                      python3 megoxer.py
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
